### ISSUE TITLE
Gurobi JLL optout still downloads artifact

### ISSUE THREAD

**Issue by noahrhodes** [jump-dev/Gurobi.jl#564] opened 2024-05-29 16:10 UTC
I am running behind a firewall that allows `github.com` but blocks `pkg.julialang.org`, meaning that I am able to add the Gurobi.jl package but unable to download the artifact.  I have set the environment variables to not use the gurobi_jll, but when adding gurobi the installation still trys to download the jll.

```
julia> ENV["GUROBI_JL_USE_GUROBI_JLL"]
"false"

julia> ENV["GUROBI_HOME"]
"/users/nrhodes/gurobi1101/linux64"

(Experiments) pkg>

(Experiments) pkg> add Gurobi
   Resolving package versions...
  Downloaded artifact: Gurobi
  Downloaded artifact: Gurobi
ERROR: Unable to automatically download/install artifact 'Gurobi' from sources listed in '/users/nrhodes/.julia/packages/Gurobi_jll/UV5wl/Artifacts.toml'.
Sources attempted:
- https://pkg.julialang.org/artifact/1cf3993225db760f620b7a50047dda0abc07e2a1
    Error: RequestError: HTTP/1.1 403 Forbidden (CONNECT tunnel failed, response 403) while requesting https://pkg.julialang.org/artifact/1cf3993225db760f620b7a50047dda0abc07e2a1
- https://anaconda.org/Gurobi/gurobi/11.0.2/download/linux-64/gurobi-11.0.2-py311_0.tar.bz2
    Error: RequestError: HTTP/1.1 403 Forbidden (CONNECT tunnel failed, response 403) while requesting https://anaconda.org/Gurobi/gurobi/11.0.2/download/linux-64/gurobi-11.0.2-py311_0.tar.bz2

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Artifacts.jl:467
  [3] download_artifacts(env::Pkg.Types.EnvCache; platform::Base.BinaryPlatforms.Platform, julia_version::VersionNumber, verbose::Bool, io::Base.TTY)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:755
  [4] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1394
...
```

**Comment by odow** [comment] 2024-05-29 20:27
Hmm. Perhaps I need to add `lazy = true`.

**Comment by odow** [comment] 2024-05-29 21:44
Could you also try starting Julia with `export JULIA_PKG_SERVER=""; julia`

**Comment by noahrhodes** [comment] 2024-05-29 22:06
with 
```
Pkg> add  Gurobi_jll#odow-patch-1
Pkg> add Gurobi
```

I get failures with `] test Gurobi` and with `using Gurobi`
(Precompile fails as it tries to download the jll from a firewall blocked location).

This happens if JULIA_PKG_SERVER is set to east/west/default/empty.

**Comment by noahrhodes** [comment] 2024-05-29 22:09
This issue isn't a very big deal for me, as I am getting a firewall rule approved for `storage.julialang.net` which is needed to download any artifacts.  It just seems like using the local gurobi version should preclude downloading the jll.

**Comment by odow** [comment] 2024-05-29 22:41
So you might need
```
] rm Gurobi
] add Gurobi_jll#odow-patch-1
ENV["GUROBI_JL_USE_GUROBI_JLL"] = "false"
] add Gurobi
```

**Comment by noahrhodes** [comment] 2024-05-30 01:18
I tried that and I still get an error after adding Gurobi.  During Gurobi pre-compilation it tries to download the jll:

```
 Precompiling project...
  ✗ Gurobi_jll
  ✗ Gurobi
  0 dependencies successfully precompiled in 12 seconds. 38 already precompiled.

ERROR: The following 2 direct dependencies failed to precompile:

Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]

Failed to precompile Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b] to "/users/nrhodes/.julia/compiled/v1.10/Gurobi/jl_iV6JDt".
ERROR: LoadError: SystemError: opening file "/users/nrhodes/.julia/packages/Gurobi/uP4zR/deps/deps.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:176
  [2] systemerror
    @ ./error.jl:175 [inlined]
  [3] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [4] open
    @ ./iostream.jl:275 [inlined]
  [5] open(f::Base.var"#433#434"{String}, args::String; kwargs::@Kwargs{})
    @ Base ./io.jl:394
  [6] open
    @ ./io.jl:393 [inlined]
  [7] read
    @ ./io.jl:486 [inlined]
  [8] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:2132
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [10] include(x::String)
    @ Gurobi ~/.julia/packages/Gurobi/uP4zR/src/Gurobi.jl:7
 [11] top-level scope
    @ ~/.julia/packages/Gurobi/uP4zR/src/Gurobi.jl:12
 [12] include
    @ ./Base.jl:495 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2222
 [14] top-level scope
    @ stdin:3
in expression starting at /users/nrhodes/.julia/packages/Gurobi/uP4zR/src/Gurobi.jl:7
in expression starting at stdin:3
Gurobi_jll [c018c7e6-a5b0-4aea-8f80-9c1ef9991411]

Failed to precompile Gurobi_jll [c018c7e6-a5b0-4aea-8f80-9c1ef9991411] to "/users/nrhodes/.julia/compiled/v1.10/Gurobi_jll/jl_IF0vbt".
 Downloading artifact: Gurobi
 Downloading artifact: Gurobi
ERROR: LoadError: Unable to automatically download/install artifact 'Gurobi' from sources listed in '/users/nrhodes/.julia/packages/Gurobi_jll/6WpUe/Artifacts.toml'.
Sources attempted:
- https://us-west.pkg.julialang.org/artifact/1cf3993225db760f620b7a50047dda0abc07e2a1
    Error: RequestError: HTTP/1.1 403 Forbidden (CONNECT tunnel failed, response 403) while requesting https://us-west.pkg.julialang.org/artifact/1cf3993225db760f620b7a50047dda0abc07e2a1
- https://anaconda.org/Gurobi/gurobi/11.0.2/download/linux-64/gurobi-11.0.2-py311_0.tar.bz2
    Error: RequestError: HTTP/1.1 403 Forbidden (CONNECT tunnel failed, response 403) while requesting https://anaconda.org/Gurobi/gurobi/11.0.2/download/linux-64/gurobi-11.0.2-py311_0.tar.bz2
...
```

**Comment by odow** [comment] 2024-05-30 01:27
I'm going to send you an email about something

**Comment by odow** [comment] 2024-05-30 01:52
Try now. I don't have a local copy of Gurobi on the server so I can't test, but:

```julia
(@v1.10) pkg> st
Status `~/.julia/environments/v1.10/Project.toml` (empty project)

(@v1.10) pkg> add Gurobi_jll#odow-patch-1 Gurobi
    Updating git-repo `https://github.com/jump-dev/Gurobi_jll.jl.git`
   Resolving package versions...
    Updating `~/.julia/environments/v1.10/Project.toml`
  [2e9cd046] + Gurobi v1.3.0
  [c018c7e6] + Gurobi_jll v11.0.2 `https://github.com/jump-dev/Gurobi_jll.jl.git#odow-patch-1`
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [6e4b80f9] + BenchmarkTools v1.5.0
  [523fee87] + CodecBzip2 v0.8.2
  [944b1d66] + CodecZlib v0.7.4
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v4.15.0
  [864edb3b] + DataStructures v0.18.20
  [163ba53b] + DiffResults v1.1.0
  [b552c78f] + DiffRules v1.15.1
  [ffbed154] + DocStringExtensions v0.9.3
  [f6369f11] + ForwardDiff v0.10.36
  [2e9cd046] + Gurobi v1.3.0
  [92d709cd] + IrrationalConstants v0.2.2
  [692b3bcd] + JLLWrappers v1.5.0
  [682c06a0] + JSON v0.21.4
  [2ab3a3ac] + LogExpFunctions v0.3.27
  [1914dd2f] + MacroTools v0.5.13
  [b8f27783] + MathOptInterface v1.30.0
  [d8a4904e] + MutableArithmetics v1.4.4
  [77ba4419] + NaNMath v1.0.2
  [bac558e1] + OrderedCollections v1.6.3
  [69de0a69] + Parsers v2.8.1
  [aea7be01] + PrecompileTools v1.2.1
  [21216c6a] + Preferences v1.4.3
  [276daf66] + SpecialFunctions v2.4.0
  [1e83bf80] + StaticArraysCore v1.4.2
  [3bb67fe8] + TranscodingStreams v0.10.8
  [6e34b625] + Bzip2_jll v1.0.8+1
  [c018c7e6] + Gurobi_jll v11.0.2 `https://github.com/jump-dev/Gurobi_jll.jl.git#odow-patch-1`
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.10.0
  [de0858da] + Printf
  [9abbd945] + Profile
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays v1.10.0
  [10745b16] + Statistics v1.10.0
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] + LibCURL_jll v8.4.0+0
  [e37daf67] + LibGit2_jll v1.6.4+0
  [29816b5a] + LibSSH2_jll v1.11.0+1
  [c8ffd9c3] + MbedTLS_jll v2.28.2+1
  [14a3606d] + MozillaCACerts_jll v2023.1.10
  [4536629a] + OpenBLAS_jll v0.3.23+4
  [05823500] + OpenLibm_jll v0.8.1+2
  [bea87d4a] + SuiteSparse_jll v7.2.1+1
  [83775a58] + Zlib_jll v1.2.13+1
  [8e850b90] + libblastrampoline_jll v5.8.0+1
  [8e850ede] + nghttp2_jll v1.52.0+1
  [3f19e933] + p7zip_jll v17.4.0+2
Precompiling project...
  ? Gurobi
```

**Comment by noahrhodes** [comment] 2024-05-30 03:03
Gurobi_jll no longer fails pre-compilation (as in it does nothing now that pre-compilation is disabled) , but Gurobi.jl still fails precompilation.  Its not clear why, but it no longer seems to have anything to do with downloading the artifact. 

```(temp) pkg> precompile Gurobi_jll

(temp) pkg> precompile Gurobi
Precompiling Gurobi
        Info Given Gurobi was explicitly requested, output will be shown live
ERROR: LoadError: SystemError: opening file "/users/nrhodes/.julia/packages/Gurobi/uP4zR/deps/deps.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:176
  [2] systemerror
    @ ./error.jl:175 [inlined]
  [3] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [4] open
    @ ./iostream.jl:275 [inlined]
  [5] open(f::Base.var"#433#434"{String}, args::String; kwargs::@Kwargs{})
    @ Base ./io.jl:394
  [6] open
    @ ./io.jl:393 [inlined]
  [7] read
    @ ./io.jl:486 [inlined]
  [8] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:2132
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [10] include(x::String)
    @ Gurobi ~/.julia/packages/Gurobi/uP4zR/src/Gurobi.jl:7
 [11] top-level scope
    @ ~/.julia/packages/Gurobi/uP4zR/src/Gurobi.jl:12
 [12] include
    @ ./Base.jl:495 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2222
 [14] top-level scope
    @ stdin:3
in expression starting at /users/nrhodes/.julia/packages/Gurobi/uP4zR/src/Gurobi.jl:7
in expression starting at stdin:3
  ✗ Gurobi
  0 dependencies successfully precompiled in 3 seconds. 38 already precompiled.

**Comment by noahrhodes** [comment] 2024-05-30 03:26
Actually, all I needed to do was run `]build ` and now it compiles + tests pass.

Everything works.

**Comment by odow** [comment] 2024-05-30 04:09
I'm going to close this in favor of https://github.com/jump-dev/Gurobi_jll.jl/pull/18. The issue is in Gurobi_jll, not Gurobi.jl

**Closed by odow** 2024-05-30 04:09 UTC
