### ISSUE TITLE
Undesired callback behavior

### ISSUE THREAD

**Issue by 1ozturkbe** [jump-dev/Gurobi.jl#395] opened 2021-02-19 22:41 UTC
Here's a MWE of the issue. I hope it is pretty straightforward. 
```julia
using JuMP
using Gurobi
m = Model(Gurobi.Optimizer)
@variable(m, x >= 1)
@objective(m, Min, x)
optimize!(m)
```
Running just the above code, if I check ``` m.moi_backend.optimizer.model.generic_callback```, I see that there is already a callback there, even though I didn't add it myself:
``` julia
Gurobi._CallbackUserData(    sense  : minimize
    number of variables             = 1
    number of linear constraints    = 0
    number of quadratic constraints = 0
    number of sos constraints       = 0
    number of non-zero coeffs       = 0
    number of non-zero qp objective terms  = 0
    number of non-zero qp constraint terms = 0...
```
For some reason, running ```optimize!``` seems to just add a generic callback. 
This is problematic, because if I try to add a callback as following:
```julia
function cb_fn(cb_data)
    val = JuMP.callback_value(x)
    con = @build_constraint(x >= 2)
    MOI.submit(m, MOI.LazyConstraint(cb_data), con)
end
MOI.set(m, MOI.LazyConstraintCallback(), cb_fn)
optimize!(m)
```
It throws the following error, since it thinks that I have both a Gurobi.CallbackFunction and an MOI one:
``` julia
ERROR: Cannot use Gurobi.CallbackFunction as well as MOI.AbstractCallbackFunction
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] _check_moi_callback_validity at C:\Users\berko\.julia\packages\Gurobi\Lci9Q\src\MOI_wrapper.jl:2372 [inlined]
 [3] optimize!(::Gurobi.Optimizer) at C:\Users\berko\.julia\packages\Gurobi\Lci9Q\src\MOI_wrapper.jl:2386
 [4] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}) at C:\Users\iai\builds\InterpretableAI\SystemImage\SysImgBuilder\.julia\packages\MathOptInterface\ZJFKw\src\Bridges\bridge_optimizer.jl:264
 [5] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at C:\Users\iai\builds\InterpretableAI\SystemImage\SysImgBuilder\.julia\packages\MathOptInterface\ZJFKw\src\Utilities\cachingoptimizer.jl:215
 [6] optimize!(::Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\iai\builds\InterpretableAI\SystemImage\SysImgBuilder\.julia\packages\JuMP\qhoVb\src\optimizer_interface.jl:130
 [7] optimize! at C:\Users\iai\builds\InterpretableAI\SystemImage\SysImgBuilder\.julia\packages\JuMP\qhoVb\src\optimizer_interface.jl:106 [inlined] (repeats 2 times)
 [8] top-level scope at REPL[61]:1
```
Furthermore, if I try to add the callback without the first ``` optimize!``` to resolve the issue, it doesn't give the right solution, and returns 1 instead of 2! Please help. I'm using Gurobi 0.9.7 and JuMP 0.21.5.

**Comment by odow** [comment] 2021-02-20 02:54
Transferred to Gurobi.jl

The issue is because of 
https://github.com/jump-dev/Gurobi.jl/blob/61b11781bf9ab6165f7bea0193a5637678182a02/src/MOI_wrapper.jl#L2385-L2398
The solution is probably just to set `has_generic_callback` back to `false` at the end of `optimize!` (but only if we set the null callback).

PRs accepted.

**Closed** 2022-02-14 18:30 UTC
Labels: bug, Wrapper: MathOptInterface, Help wanted!
