### ISSUE TITLE
Result not deterministic

### ISSUE THREAD

**Issue by guberger** [jump-dev/Gurobi.jl#481] opened 2022-06-09 15:46 UTC
I used Gurobi, via JuMP (`model = direct_model(Gurobi.Optimizer())`), to solve the problem attached below.
However, the output was not deterministic: run several times on the same computer, it provided different outputs.
It looks like the solver was using different methods: started with "Barrier" (sometimes with "Crossover" needed, sometimes not), and sometimes switching to "Dual Simplex", in a way that looked unpredictable.

For instance, by setting the `"Method"` attributes to `2` (Barrier), it seemed to become determinisitc.

[model_gurobi.txt](https://github.com/jump-dev/Gurobi.jl/files/8871863/model_gurobi.txt)

**Comment by mlubin** [comment] 2022-06-09 20:09
This is Gurobi's intended behavior, please see the documentation for [`Method`](https://www.gurobi.com/documentation/9.5/refman/method.html). (Closing as not a Gurobi.jl issue.)

**Closed by mlubin** 2022-06-09 20:09 UTC

**Comment by guberger** [comment] 2022-06-09 20:14
Indeed, I should have read the doc of `Method` for just one more paragraph. Sorry about that...
